import { Inter } from 'next/font/google'
import Footer from './Footer'
import NavBar from './NavBar'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Test App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
    <NavBar/>
      <body className={inter.className}>{children}</body>
    <Footer />
    </>
  )
}
